//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Ad
    {
        public int ID { get; set; }
        public string URL { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> UploadPeople { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string AdName { get; set; }
        public Nullable<int> Enabled { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Title { get; set; }
    }
}
