//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_DevsInfo
    {
        public int UserID { get; set; }
        public string Address { get; set; }
        public string UnitName { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Contact { get; set; }
    }
}
