//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_LedAd
    {
        public int ID { get; set; }
        public string CompanyName { get; set; }
        public string AdName { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Y { get; set; }
        public Nullable<int> X { get; set; }
        public string Contents { get; set; }
        public Nullable<int> DateEnable { get; set; }
        public Nullable<int> WeatherEnable { get; set; }
        public string Rmearks { get; set; }
        public string PushPlanConfig { get; set; }
        public Nullable<int> SendEnable { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
