//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_RecordFile
    {
        public int ID { get; set; }
        public string DeviceSN { get; set; }
        public Nullable<System.DateTime> RecvDate { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public string OrderID { get; set; }
        public Nullable<int> ChannelID { get; set; }
        public Nullable<int> DoorID { get; set; }
        public string FilePath { get; set; }
    }
}
