//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Users_LcdAd
    {
        public int ID { get; set; }
        public Nullable<int> LcdID { get; set; }
        public Nullable<int> PlanID { get; set; }
        public Nullable<int> DevicetID { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
