//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Device_Logs_Parking_User
    {
        public Nullable<int> ID { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public string DeviceSN { get; set; }
        public string DeviceName { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> Channel { get; set; }
        public Nullable<int> Confidence { get; set; }
        public string License { get; set; }
        public Nullable<int> PlateType { get; set; }
        public string Location { get; set; }
        public string PlateColor { get; set; }
        public Nullable<int> CarType { get; set; }
        public Nullable<System.DateTime> Recotime { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public string ImageFull { get; set; }
        public string ImageSmall { get; set; }
        public string JSON { get; set; }
        public int UserID { get; set; }
    }
}
