//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_FP_SensorLog
    {
        public int UserID { get; set; }
        public string IPAddress { get; set; }
        public string Mac { get; set; }
        public System.DateTime EventTime { get; set; }
        public int Channel { get; set; }
        public int nIn { get; set; }
        public int nOut { get; set; }
        public double InSpeed { get; set; }
        public double OutSpeed { get; set; }
        public int ZoneNum { get; set; }
        public int DataID { get; set; }
        public Nullable<int> DeviceID { get; set; }
    }
}
