//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_FP_Status_Ticket
    {
        public Nullable<long> rowNum { get; set; }
        public int DeviceID { get; set; }
        public string DeviceSN { get; set; }
        public string DeviceName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int Enabled { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> UICount { get; set; }
        public Nullable<int> UIID { get; set; }
        public Nullable<decimal> Lng { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public int Version { get; set; }
        public string Config { get; set; }
        public Nullable<int> LedID { get; set; }
        public Nullable<int> DvrID { get; set; }
        public string Remarks { get; set; }
        public int SystemType { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int PassCount { get; set; }
        public int checkCount { get; set; }
        public int ChannelMode { get; set; }
        public System.DateTime Startup { get; set; }
    }
}
