//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_FP_TicketUI
    {
        public int DeviceID { get; set; }
        public string DeviceSN { get; set; }
        public string DeviceName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int Enabled { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public int SystemType { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> DvrID { get; set; }
        public Nullable<int> LedID { get; set; }
        public string Config { get; set; }
        public int Version { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public Nullable<decimal> Lng { get; set; }
        public Nullable<int> UIID { get; set; }
        public Nullable<int> UICount { get; set; }
        public string ADText { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public string UIName { get; set; }
        public string UIData { get; set; }
        public string Expr1 { get; set; }
        public Nullable<int> UIVersion { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> Expr2 { get; set; }
    }
}
